baseURL = 'https://kvso755.github.io/Pagina-Hugo/'
languageCode = 'es-mx'
title = 'Pagina Web De la Trackalosa'
theme = 'ananke'

[params]
  site_logo = ''
  description = 'Ingenieria en Software -  Tralalero Tralala'
  background_color_class = 'bg-dark-red'